/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.Gestor;
import dto.ProduccionOperario;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.Timer;
import javax.swing.table.DefaultTableModel;
import models.Responsable;


/**
 *
 * @author IVAN
 */
public final class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    
    
    ArrayList<ProduccionOperario> lista;
    Timer count, timer;
    int i = 10;
    
    public Consultas() {
        initComponents();
        cargarCombo();
        llenarTabla();
        autoRefrescar();
    }
    
    public void cargarCombo() {
        Gestor gestor = new Gestor();
        ArrayList<Responsable> responsables = gestor.obtenerResponsables();
        DefaultComboBoxModel modelR = new DefaultComboBoxModel();
        for (Responsable responsable : responsables) {
            modelR.addElement(responsable);
        }
        cmbResponsables.setModel(modelR);
    }
    
    public void llenarTabla() {
        Gestor gestor = new Gestor();
        Responsable r = (Responsable)this.cmbResponsables.getSelectedItem();
        lista = gestor.obtenerProduccionOperario(r.getId());
        
        String titulos[] = {"Fecha", "Componentes", "Cantidad"};
        
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(titulos);
        
        for (ProduccionOperario po : lista) {
            model.addRow(new Object[] { po.getFecha(), po.getDescComponente(), po.getCantidadProduccion() });
        }
        
        tabla.setModel(model);
    }
    
    public void autoRefrescar() {
             
        count = new Timer();
        count.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                btnRefrescar.setText(Integer.toString(i));
                if(i > 0) {
                i = i - 1;
                           }
                else {
                    btnRefrescar.setText("Refrescando");
                    i = 10;
                }
          }
        }, 0, 1000);
        
       timer = new Timer(); 
       timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                llenarTabla();
            }
        }, 10000, 10000);
      
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cmbResponsables = new javax.swing.JComboBox<>();
        btnMenu = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        cmbResponsables.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbResponsables.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbResponsablesItemStateChanged(evt);
            }
        });

        btnMenu.setText("< Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnReport.setText("Reporte");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRefrescar.setText("Refrescar");
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbResponsables, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMenu)
                        .addGap(11, 11, 11)
                        .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnReport)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(cmbResponsables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu)
                    .addComponent(btnRefrescar)
                    .addComponent(btnEditar)
                    .addComponent(btnReport))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnRefrescar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbResponsablesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbResponsablesItemStateChanged
        llenarTabla();
    }//GEN-LAST:event_cmbResponsablesItemStateChanged

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setEnabled(true);
        menu.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        Reportes reporte = new Reportes();
        reporte.setEnabled(true);
        reporte.setVisible(true);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tabla.getSelectedRow();
        ProduccionOperario po = (ProduccionOperario)lista.get(fila);
        
        if(po != null) {
            Alta alta = new Alta(po);
            alta.setEnabled(true);
            alta.setVisible(true);
        }
        else 
            JOptionPane.showMessageDialog(this, "No seleccionaste ningún elemento");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        i = 10;
        llenarTabla();
        count.cancel();
        timer.cancel();
        autoRefrescar();
      
    }//GEN-LAST:event_btnRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnReport;
    private javax.swing.JComboBox<String> cmbResponsables;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
